//------------------------------------------------------------------------------
// <auto-generated>
// Layers.cs
// This code was generated by ScriptForge. To rebuild the code go to 
// Project Settings ->Script Forge and on that window hit generate all. Any
// changes made to this script will be overwritten.  
// Asset Hash: True4LayersTrue4LayersTrue4LayersTrue4LayersTrue4LayersAssets/Code/Layers.csTrueFalseDefaultTransparentFXIgnore_RaycastWaterUIPlayerEnemyObstacleProjectilePlayerProjectileEnemyAssets/Code/Layers.csTrueFalseDefaultTransparentFXIgnore_RaycastWaterUIPlayerEnemyObstacleProjectilePostProcessAssets/Code/Layers.csTrueFalseDefaultTransparentFXIgnore_RaycastWaterUIPlayerEnemyObstacleProjectilePostProcessAssets/Code/Layers.csTrueFalseDefaultTransparentFXIgnore_RaycastWaterUIPlayerEnemyObstacleEnemyProjectilePlayerProjectilePostProcessAssets/Code/Layers.csTrueFalseDefaultTransparentFXIgnore_RaycastWaterUIPlayerEnemyObstacleProjectilePostProcess
// </auto-generated>
//------------------------------------------------------------------------------
public static class Layers
{
    /// <summary>
    /// An enum that contains the names of every layer that
    /// is in your project.
    /// </summary>
    public enum Enum
    {
        Default = 0,
        TransparentFX = 1,
        Ignore_Raycast = 2,
        Water = 4,
        UI = 5,
        Player = 8,
        Enemy = 9,
        Obstacle = 10,
        EnemyProjectile = 11,
        PlayerProjectile = 12,
        Postprocess = 13,
    }

    public static class Int
    {
        public const int Default = 0;
        public const int TransparentFX = 1;
        public const int Ignore_Raycast = 2;
        public const int Water = 4;
        public const int UI = 5;
        public const int Player = 8;
        public const int Enemy = 9;
        public const int Obstacle = 10;
        public const int EnemyProjectile = 11;
        public const int PlayerProjectile = 12;
        public const int Postprocess = 13;
    }
    public static class Bit
    {
        public const int Default = 1 << 0;
        public const int TransparentFX = 1 << 1;
        public const int Ignore_Raycast = 1 << 2;
        public const int Water = 1 << 4;
        public const int UI = 1 << 5;
        public const int Player = 1 << 8;
        public const int Enemy = 1 << 9;
        public const int Obstacle = 1 << 10;
        public const int EnemyProjectile = 1 << 11;
        public const int PlayerProjectile = 1 << 12;
        public const int Postprocess = 1 << 13;
    }
}